In [5]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict

def find_repo_root(start=None, markers=('.git', 'environment.yml', 'requirements.txt', 'README.md')):
    """Walk upward from `start` (or cwd) until a marker file/dir is found.
    Returns absolute path to repo root or None if not found.
    """
    if start is None:
        start = os.getcwd()
    cur = os.path.abspath(start)
    while True:
        for m in markers:
            if os.path.exists(os.path.join(cur, m)):
                return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            return None
        cur = parent

repo_root = find_repo_root()
if repo_root is None:
    # fallback to repository parent heuristics
    repo_root = os.path.abspath(os.path.join(os.getcwd(), '..'))

# canonical path to materials.csv inside repo: data/raw/materials.csv
DATA_PATH = os.path.join(repo_root, 'data', 'raw', 'materials.csv')
if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(f"materials.csv not found at {DATA_PATH}. Checked repo root: {repo_root}")

print('Using data:', DATA_PATH)

Using data: /Users/nk/Downloads/GNN/xtrium-material-gnn/data/raw/materials.csv

In [ ]:

try:
    df = pd.read_csv(DATA_PATH)
    print('Loaded dataframe with', len(df), 'rows')
    display(df.head())
except Exception as e:
    raise RuntimeError(f'Failed to load {DATA_PATH}: {e}')

Loaded dataframe with 30 rows

,Id,Material_Name,Database_Source,Category,URL,Name,Database,Composition,Manufacturer,Technical_Readiness_Level,...,Replacement_Fraction_per_Flight_Value,Replacement_Fraction_per_Flight_Units,Replacement_Fraction_per_Flight_Source,Replacement_Fraction_per_Flight_STP,Replacement_Fraction_per_Flight_Last_Modified,Reuse_Flight_Limit_of_flights_Value,Reuse_Flight_Limit_of_flights_Units,Reuse_Flight_Limit_of_flights_Source,Reuse_Flight_Limit_of_flights_STP,Reuse_Flight_Limit_of_flights_Last_Modified
0,1,"1/4"" Rohacell 31 foam/carbon cloth Aircraft Sk...",NASA Langley Research Center Database,Structural Organic Composites | Description:,https://tpsx.arc.nasa.gov/Material?id=1547,"1/4"" Rohacell 31 foam/carbon cloth Aircraft Sk...",NASA Langley Research Center Database | Descri...,Description:,Description:,4 | Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1437,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1441,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1440,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1438,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(30, 255)

In [8]:

display(df.head(10))
display(df.dtypes)

,Id,Material_Name,Database_Source,Category,URL,Name,Database,Composition,Manufacturer,Technical_Readiness_Level,...,Replacement_Fraction_per_Flight_Value,Replacement_Fraction_per_Flight_Units,Replacement_Fraction_per_Flight_Source,Replacement_Fraction_per_Flight_STP,Replacement_Fraction_per_Flight_Last_Modified,Reuse_Flight_Limit_of_flights_Value,Reuse_Flight_Limit_of_flights_Units,Reuse_Flight_Limit_of_flights_Source,Reuse_Flight_Limit_of_flights_STP,Reuse_Flight_Limit_of_flights_Last_Modified
0,1,"1/4"" Rohacell 31 foam/carbon cloth Aircraft Sk...",NASA Langley Research Center Database,Structural Organic Composites | Description:,https://tpsx.arc.nasa.gov/Material?id=1547,"1/4"" Rohacell 31 foam/carbon cloth Aircraft Sk...",NASA Langley Research Center Database | Descri...,Description:,Description:,4 | Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1437,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1441,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1440,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1438,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1439,"1,3-Bis(3,4-dicarboxyphenoxy-4-phenyl-2-propyl...",NASA Langley Research Center Database | Descri...,"Composition of BMDEDA - 1,3-Bis(3,4-dicarboxyp...","1,3-Bis(4-hydroxyphenyl-2-propyl)benzene (bish...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,"3,3',4,4'-Benzophenone tetracarboxylic dianhyd...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1499,"3,3',4,4'-Benzophenone tetracarboxylic dianhyd...",NASA Langley Research Center Database | Descri...,Description:,"4,4'-Oxydiphthalic anhydride (ODPA) and Hydro...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,35v/o SCS-9a-(20v/oRBSiC/ZrB2),NASA Ames Thermal Protection Materials,Ultra-High Temperature Ceramics | Description:,https://tpsx.arc.nasa.gov/Material?id=31,35v/o SCS-9a-(20v/oRBSiC/ZrB2) | Description:,NASA Ames Thermal Protection Materials | Descr...,Description:,"Advanced Ceramics Research, Tucson, Arizona. |...",Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,"4,4'-(2-diphenylphosphinyl-1,4-phenylenedioxy)...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1494,"4,4'-(2-diphenylphosphinyl-1,4-phenylenedioxy)...",NASA Langley Research Center Database | Descri...,Description:,Description:,3 | Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,"4,4'-(2-diphenylphosphinyl-1,4-phenylenedioxy)...",NASA Langley Research Center Database,Polyamides | Description:,https://tpsx.arc.nasa.gov/Material?id=1495,"4,4'-(2-diphenylphosphinyl-1,4-phenylenedioxy)...",NASA Langley Research Center Database | Descri...,Description:,Description:,3 | Description:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Id                                               int64
Material_Name                                   object
Database_Source                                 object
Category                                        object
URL                                             object
                                                ...
Reuse_Flight_Limit_of_flights_Value            float64
Reuse_Flight_Limit_of_flights_Units             object
Reuse_Flight_Limit_of_flights_Source            object
Reuse_Flight_Limit_of_flights_STP               object
Reuse_Flight_Limit_of_flights_Last_Modified     object
Length: 255, dtype: object

In [9]:
missing = df.isnull().mean().sort_values(ascending=False)
print("Top missing cols:\n", missing.head(20))
numeric = df.select_dtypes(include=['float','int'])
display(numeric.describe().T)

Top missing cols:
 Tensile_Modulus_Thru_the_Thickness_10_Value            0.966667
Compressive_Strength_In_Plane_STP                      0.966667
Tensile_Modulus_Thru_the_Thickness_10_STP              0.966667
Tensile_Modulus_Thru_the_Thickness_10_Last_Modified    0.966667
Tensile_Modulus_In_Plane_11_Value                      0.966667
Tensile_Modulus_In_Plane_11_Units                      0.966667
Tensile_Modulus_In_Plane_11_Source                     0.966667
Tensile_Modulus_In_Plane_11_STP                        0.966667
Tensile_Modulus_In_Plane_11_Last_Modified              0.966667
Compressive_Strength_In_Plane_Value                    0.966667
Compressive_Strength_In_Plane_Units                    0.966667
Compressive_Strength_In_Plane_Source                   0.966667
Compressive_Strength_In_Plane_Reference                0.966667
Poisson_s_Ratio_Isotropic_13_Last_Modified             0.966667
Compressive_Strength_In_Plane_Last_Modified            0.966667
Shear_Strength_Isotropic_12_Value                      0.966667
Shear_Strength_Isotropic_12_Units                      0.966667
Shear_Strength_Isotropic_12_Source                     0.966667
Shear_Strength_Isotropic_12_STP                        0.966667
Shear_Strength_Isotropic_12_Reference                  0.966667
dtype: float64

,count,mean,std,min,25%,50%,75%,max
Id,30.0,15.500000,8.803408,1.0000,8.2500,15.5000,22.7500,30.0000
Density_Value,15.0,1367.533333,691.259603,288.0000,1120.0000,1240.0000,1450.0000,3600.0000
Density_Uncertainty,1.0,1.440000,NaN,1.4400,1.4400,1.4400,1.4400,1.4400
Density_Reference,8.0,1.000000,0.000000,1.0000,1.0000,1.0000,1.0000,1.0000
Thermal_Conductivity_Thru_the_Thickness_Value,1.0,0.107000,NaN,0.1070,0.1070,0.1070,0.1070,0.1070
...,...,...,...,...,...,...,...,...
Purchase_Cost_Value,1.0,129000.000000,NaN,129000.0000,129000.0000,129000.0000,129000.0000,129000.0000
Installation_Time_Value,1.0,372000.000000,NaN,372000.0000,372000.0000,372000.0000,372000.0000,372000.0000
Inspection_Repair_Time_per_Flight_Value,1.0,4260.000000,NaN,4260.0000,4260.0000,4260.0000,4260.0000,4260.0000
Replacement_Fraction_per_Flight_Value,1.0,0.001300,NaN,0.0013,0.0013,0.0013,0.0013,0.0013
Reuse_Flight_Limit_of_flights_Value,1.0,100.000000,NaN,100.0000,100.0000,100.0000,100.0000,100.0000

In [10]:
text_cols = [c for c in df.columns if df[c].dtype=="object" and df[c].nunique()>20]
cat_cols  = [c for c in df.columns if df[c].dtype=="object" and df[c].nunique()<=20]
num_cols  = numeric.columns.tolist()
print("Text cols:", text_cols)
print("Categorical cols:", cat_cols)
print("Numeric cols:", num_cols)

Text cols: ['Material_Name', 'URL', 'Name', 'Description']
Categorical cols: ['Database_Source', 'Category', 'Database', 'Composition', 'Manufacturer', 'Technical_Readiness_Level', 'Last_Modified', 'Point_of_Contact', 'Property_References', 'General_References', 'Density_Units', 'Density_Source', 'Density_STP', 'Density_Last_Modified', 'Thermal_Conductivity_Thru_the_Thickness_Units', 'Thermal_Conductivity_Thru_the_Thickness_Source', 'Thermal_Conductivity_Thru_the_Thickness_STP', 'Thermal_Conductivity_Thru_the_Thickness_Last_Modified', 'Thermal_Conductivity_In_Plane_Units', 'Thermal_Conductivity_In_Plane_Source', 'Thermal_Conductivity_In_Plane_STP', 'Thermal_Conductivity_In_Plane_Last_Modified', 'Specific_Heat_Units', 'Specific_Heat_Source', 'Specific_Heat_STP', 'Specific_Heat_Last_Modified', 'Notes', 'Tensile_Strength_Isotropic_1_Units', 'Tensile_Strength_Isotropic_1_Source', 'Tensile_Strength_Isotropic_1_STP', 'Tensile_Strength_Isotropic_1_Last_Modified', 'Tensile_Yield_Strength_Isotropic_2_Units', 'Tensile_Yield_Strength_Isotropic_2_Source', 'Tensile_Yield_Strength_Isotropic_2_STP', 'Tensile_Yield_Strength_Isotropic_2_Last_Modified', 'Tensile_Modulus_In_Plane_3_Units', 'Tensile_Modulus_In_Plane_3_Source', 'Tensile_Modulus_In_Plane_3_STP', 'Tensile_Modulus_In_Plane_3_Last_Modified', 'Tensile_Modulus_Isotropic_2_Units', 'Tensile_Modulus_Isotropic_2_Source', 'Tensile_Modulus_Isotropic_2_STP', 'Tensile_Modulus_Isotropic_2_Last_Modified', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Units', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Source', 'Coefficient_of_Thermal_Expansion_Isotropic_3_STP', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Last_Modified', 'Pictures', 'Thermal_Conductivity_Thru_the_Thickness_1_Units', 'Thermal_Conductivity_Thru_the_Thickness_1_Source', 'Thermal_Conductivity_Thru_the_Thickness_1_STP', 'Thermal_Conductivity_Thru_the_Thickness_1_Last_Modified', 'Thermal_Conductivity_In_Plane_2_Units', 'Thermal_Conductivity_In_Plane_2_Source', 'Thermal_Conductivity_In_Plane_2_STP', 'Thermal_Conductivity_In_Plane_2_Last_Modified', 'Emissivity3_Units', 'Emissivity3_Source', 'Emissivity3_STP', 'Emissivity3_Last_Modified', 'Multiple_Use_Temperature_Limit4_Units', 'Multiple_Use_Temperature_Limit4_Source', 'Multiple_Use_Temperature_Limit4_STP', 'Multiple_Use_Temperature_Limit4_Last_Modified', 'Single_Use_Temperature_Limit5_Units', 'Single_Use_Temperature_Limit5_Source', 'Single_Use_Temperature_Limit5_STP', 'Single_Use_Temperature_Limit5_Last_Modified', 'Eutectic_Temperature_Limit6_Units', 'Eutectic_Temperature_Limit6_Source', 'Eutectic_Temperature_Limit6_STP', 'Eutectic_Temperature_Limit6_Last_Modified', 'Melt_Temperature7_Units', 'Melt_Temperature7_Source', 'Melt_Temperature7_STP', 'Melt_Temperature7_Last_Modified', 'Tensile_Strength_Thru_the_Thickness_8_Units', 'Tensile_Strength_Thru_the_Thickness_8_Source', 'Tensile_Strength_Thru_the_Thickness_8_STP', 'Tensile_Strength_Thru_the_Thickness_8_Last_Modified', 'Tensile_Strength_In_Plane_9_Units', 'Tensile_Strength_In_Plane_9_Source', 'Tensile_Strength_In_Plane_9_STP', 'Tensile_Strength_In_Plane_9_Last_Modified', 'Tensile_Modulus_Thru_the_Thickness_10_Units', 'Tensile_Modulus_Thru_the_Thickness_10_Source', 'Tensile_Modulus_Thru_the_Thickness_10_STP', 'Tensile_Modulus_Thru_the_Thickness_10_Last_Modified', 'Tensile_Modulus_In_Plane_11_Units', 'Tensile_Modulus_In_Plane_11_Source', 'Tensile_Modulus_In_Plane_11_STP', 'Tensile_Modulus_In_Plane_11_Last_Modified', 'Compressive_Strength_In_Plane_Units', 'Compressive_Strength_In_Plane_Source', 'Compressive_Strength_In_Plane_STP', 'Compressive_Strength_In_Plane_Last_Modified', 'Shear_Strength_Isotropic_12_Units', 'Shear_Strength_Isotropic_12_Source', 'Shear_Strength_Isotropic_12_STP', 'Shear_Strength_Isotropic_12_Last_Modified', 'Poisson_s_Ratio_Isotropic_13_Units', 'Poisson_s_Ratio_Isotropic_13_Source', 'Poisson_s_Ratio_Isotropic_13_STP', 'Poisson_s_Ratio_Isotropic_13_Last_Modified', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Units', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Source', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_STP', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Last_Modified', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Units', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Source', 'Coefficient_of_Thermal_Expansion_In_Plane_15_STP', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Last_Modified', 'Emissivity1_Units', 'Emissivity1_Source', 'Emissivity1_STP', 'Emissivity1_Last_Modified', 'Absorptivity2_Units', 'Absorptivity2_Source', 'Absorptivity2_STP', 'Absorptivity2_Last_Modified', 'Tensile_Strength_Isotropic_3_Units', 'Tensile_Strength_Isotropic_3_Source', 'Tensile_Strength_Isotropic_3_STP', 'Tensile_Strength_Isotropic_3_Last_Modified', 'Tensile_Modulus_Isotropic_4_Units', 'Tensile_Modulus_Isotropic_4_Source', 'Tensile_Modulus_Isotropic_4_STP', 'Tensile_Modulus_Isotropic_4_Last_Modified', 'Thermal_Conductivity_Isotropic_1_Units', 'Thermal_Conductivity_Isotropic_1_Source', 'Thermal_Conductivity_Isotropic_1_STP', 'Thermal_Conductivity_Isotropic_1_Last_Modified', 'Specific_Heat2_Units', 'Specific_Heat2_Source', 'Specific_Heat2_STP', 'Specific_Heat2_Last_Modified', 'Thermal_Conductivity_Isotropic_Units', 'Thermal_Conductivity_Isotropic_Source', 'Thermal_Conductivity_Isotropic_STP', 'Thermal_Conductivity_Isotropic_Last_Modified', 'Emissivity_Units', 'Emissivity_Source', 'Emissivity_STP', 'Emissivity_Last_Modified', 'Single_Use_Temperature_Limit_Units', 'Single_Use_Temperature_Limit_Source', 'Single_Use_Temperature_Limit_STP', 'Single_Use_Temperature_Limit_Last_Modified', 'Multiple_Use_Temperature_Limit_Units', 'Multiple_Use_Temperature_Limit_Source', 'Multiple_Use_Temperature_Limit_STP', 'Multiple_Use_Temperature_Limit_Last_Modified', 'Purchase_Cost_Units', 'Purchase_Cost_Source', 'Purchase_Cost_STP', 'Purchase_Cost_Last_Modified', 'Installation_Time_Units', 'Installation_Time_Source', 'Installation_Time_STP', 'Installation_Time_Last_Modified', 'Inspection_Repair_Time_per_Flight_Units', 'Inspection_Repair_Time_per_Flight_Source', 'Inspection_Repair_Time_per_Flight_STP', 'Inspection_Repair_Time_per_Flight_Last_Modified', 'Replacement_Fraction_per_Flight_Units', 'Replacement_Fraction_per_Flight_Source', 'Replacement_Fraction_per_Flight_STP', 'Replacement_Fraction_per_Flight_Last_Modified', 'Reuse_Flight_Limit_of_flights_Units', 'Reuse_Flight_Limit_of_flights_Source', 'Reuse_Flight_Limit_of_flights_STP', 'Reuse_Flight_Limit_of_flights_Last_Modified']
Numeric cols: ['Id', 'Density_Value', 'Density_Uncertainty', 'Density_Reference', 'Thermal_Conductivity_Thru_the_Thickness_Value', 'Thermal_Conductivity_Thru_the_Thickness_Uncertainty', 'Thermal_Conductivity_Thru_the_Thickness_Reference', 'Thermal_Conductivity_In_Plane_Value', 'Thermal_Conductivity_In_Plane_Uncertainty', 'Thermal_Conductivity_In_Plane_Reference', 'Specific_Heat_Value', 'Specific_Heat_Uncertainty', 'Specific_Heat_Reference', 'Tensile_Strength_Isotropic_1_Value', 'Tensile_Strength_Isotropic_1_Uncertainty', 'Tensile_Strength_Isotropic_1_Reference', 'Tensile_Yield_Strength_Isotropic_2_Value', 'Tensile_Yield_Strength_Isotropic_2_Uncertainty', 'Tensile_Yield_Strength_Isotropic_2_Reference', 'Tensile_Modulus_In_Plane_3_Value', 'Tensile_Modulus_In_Plane_3_Uncertainty', 'Tensile_Modulus_In_Plane_3_Reference', 'Tensile_Modulus_Isotropic_2_Value', 'Tensile_Modulus_Isotropic_2_Uncertainty', 'Tensile_Modulus_Isotropic_2_Reference', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Value', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Uncertainty', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Reference', 'Thermal_Conductivity_Thru_the_Thickness_1_Value', 'Thermal_Conductivity_In_Plane_2_Value', 'Emissivity3_Value', 'Multiple_Use_Temperature_Limit4_Value', 'Single_Use_Temperature_Limit5_Value', 'Eutectic_Temperature_Limit6_Value', 'Melt_Temperature7_Value', 'Tensile_Strength_Thru_the_Thickness_8_Value', 'Tensile_Strength_Thru_the_Thickness_8_Reference', 'Tensile_Strength_In_Plane_9_Value', 'Tensile_Strength_In_Plane_9_Reference', 'Tensile_Modulus_Thru_the_Thickness_10_Value', 'Tensile_Modulus_In_Plane_11_Value', 'Compressive_Strength_In_Plane_Value', 'Compressive_Strength_In_Plane_Reference', 'Shear_Strength_Isotropic_12_Value', 'Shear_Strength_Isotropic_12_Reference', 'Poisson_s_Ratio_Isotropic_13_Value', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Value', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Reference', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Value', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Reference', 'Emissivity1_Value', 'Emissivity1_Uncertainty', 'Emissivity1_Reference', 'Absorptivity2_Value', 'Absorptivity2_Uncertainty', 'Absorptivity2_Reference', 'Tensile_Strength_Isotropic_3_Value', 'Tensile_Strength_Isotropic_3_Uncertainty', 'Tensile_Strength_Isotropic_3_Reference', 'Tensile_Modulus_Isotropic_4_Value', 'Tensile_Modulus_Isotropic_4_Uncertainty', 'Tensile_Modulus_Isotropic_4_Reference', 'Thermal_Conductivity_Isotropic_1_Value', 'Thermal_Conductivity_Isotropic_1_Reference', 'Specific_Heat2_Value', 'Specific_Heat2_Reference', 'Thermal_Conductivity_Isotropic_Value', 'Thermal_Conductivity_Isotropic_Reference', 'Emissivity_Value', 'Emissivity_Reference', 'Single_Use_Temperature_Limit_Value', 'Single_Use_Temperature_Limit_Reference', 'Thermal_Conductivity_Isotropic_Uncertainty', 'Multiple_Use_Temperature_Limit_Value', 'Purchase_Cost_Value', 'Installation_Time_Value', 'Inspection_Repair_Time_per_Flight_Value', 'Replacement_Fraction_per_Flight_Value', 'Reuse_Flight_Limit_of_flights_Value']

In [11]:
print("Column sample names:", df.columns.tolist())
prop_candidates = [c for c in df.columns if any(unit in c.lower() for unit in ['mpa','pa','kg','g','m3','%','wt'])]
print("Prop name candidates:", prop_candidates)

Column sample names: ['Id', 'Material_Name', 'Database_Source', 'Category', 'URL', 'Name', 'Database', 'Composition', 'Manufacturer', 'Technical_Readiness_Level', 'Last_Modified', 'Description', 'Point_of_Contact', 'Property_References', 'General_References', 'Density_Value', 'Density_Units', 'Density_Uncertainty', 'Density_Source', 'Density_STP', 'Density_Reference', 'Density_Last_Modified', 'Thermal_Conductivity_Thru_the_Thickness_Value', 'Thermal_Conductivity_Thru_the_Thickness_Units', 'Thermal_Conductivity_Thru_the_Thickness_Uncertainty', 'Thermal_Conductivity_Thru_the_Thickness_Source', 'Thermal_Conductivity_Thru_the_Thickness_STP', 'Thermal_Conductivity_Thru_the_Thickness_Reference', 'Thermal_Conductivity_Thru_the_Thickness_Last_Modified', 'Thermal_Conductivity_In_Plane_Value', 'Thermal_Conductivity_In_Plane_Units', 'Thermal_Conductivity_In_Plane_Uncertainty', 'Thermal_Conductivity_In_Plane_Source', 'Thermal_Conductivity_In_Plane_STP', 'Thermal_Conductivity_In_Plane_Reference', 'Thermal_Conductivity_In_Plane_Last_Modified', 'Specific_Heat_Value', 'Specific_Heat_Units', 'Specific_Heat_Uncertainty', 'Specific_Heat_Source', 'Specific_Heat_STP', 'Specific_Heat_Reference', 'Specific_Heat_Last_Modified', 'Notes', 'Tensile_Strength_Isotropic_1_Value', 'Tensile_Strength_Isotropic_1_Units', 'Tensile_Strength_Isotropic_1_Uncertainty', 'Tensile_Strength_Isotropic_1_Source', 'Tensile_Strength_Isotropic_1_STP', 'Tensile_Strength_Isotropic_1_Reference', 'Tensile_Strength_Isotropic_1_Last_Modified', 'Tensile_Yield_Strength_Isotropic_2_Value', 'Tensile_Yield_Strength_Isotropic_2_Units', 'Tensile_Yield_Strength_Isotropic_2_Uncertainty', 'Tensile_Yield_Strength_Isotropic_2_Source', 'Tensile_Yield_Strength_Isotropic_2_STP', 'Tensile_Yield_Strength_Isotropic_2_Reference', 'Tensile_Yield_Strength_Isotropic_2_Last_Modified', 'Tensile_Modulus_In_Plane_3_Value', 'Tensile_Modulus_In_Plane_3_Units', 'Tensile_Modulus_In_Plane_3_Uncertainty', 'Tensile_Modulus_In_Plane_3_Source', 'Tensile_Modulus_In_Plane_3_STP', 'Tensile_Modulus_In_Plane_3_Reference', 'Tensile_Modulus_In_Plane_3_Last_Modified', 'Tensile_Modulus_Isotropic_2_Value', 'Tensile_Modulus_Isotropic_2_Units', 'Tensile_Modulus_Isotropic_2_Uncertainty', 'Tensile_Modulus_Isotropic_2_Source', 'Tensile_Modulus_Isotropic_2_STP', 'Tensile_Modulus_Isotropic_2_Reference', 'Tensile_Modulus_Isotropic_2_Last_Modified', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Value', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Units', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Uncertainty', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Source', 'Coefficient_of_Thermal_Expansion_Isotropic_3_STP', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Reference', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Last_Modified', 'Pictures', 'Thermal_Conductivity_Thru_the_Thickness_1_Value', 'Thermal_Conductivity_Thru_the_Thickness_1_Units', 'Thermal_Conductivity_Thru_the_Thickness_1_Source', 'Thermal_Conductivity_Thru_the_Thickness_1_STP', 'Thermal_Conductivity_Thru_the_Thickness_1_Last_Modified', 'Thermal_Conductivity_In_Plane_2_Value', 'Thermal_Conductivity_In_Plane_2_Units', 'Thermal_Conductivity_In_Plane_2_Source', 'Thermal_Conductivity_In_Plane_2_STP', 'Thermal_Conductivity_In_Plane_2_Last_Modified', 'Emissivity3_Value', 'Emissivity3_Units', 'Emissivity3_Source', 'Emissivity3_STP', 'Emissivity3_Last_Modified', 'Multiple_Use_Temperature_Limit4_Value', 'Multiple_Use_Temperature_Limit4_Units', 'Multiple_Use_Temperature_Limit4_Source', 'Multiple_Use_Temperature_Limit4_STP', 'Multiple_Use_Temperature_Limit4_Last_Modified', 'Single_Use_Temperature_Limit5_Value', 'Single_Use_Temperature_Limit5_Units', 'Single_Use_Temperature_Limit5_Source', 'Single_Use_Temperature_Limit5_STP', 'Single_Use_Temperature_Limit5_Last_Modified', 'Eutectic_Temperature_Limit6_Value', 'Eutectic_Temperature_Limit6_Units', 'Eutectic_Temperature_Limit6_Source', 'Eutectic_Temperature_Limit6_STP', 'Eutectic_Temperature_Limit6_Last_Modified', 'Melt_Temperature7_Value', 'Melt_Temperature7_Units', 'Melt_Temperature7_Source', 'Melt_Temperature7_STP', 'Melt_Temperature7_Last_Modified', 'Tensile_Strength_Thru_the_Thickness_8_Value', 'Tensile_Strength_Thru_the_Thickness_8_Units', 'Tensile_Strength_Thru_the_Thickness_8_Source', 'Tensile_Strength_Thru_the_Thickness_8_STP', 'Tensile_Strength_Thru_the_Thickness_8_Reference', 'Tensile_Strength_Thru_the_Thickness_8_Last_Modified', 'Tensile_Strength_In_Plane_9_Value', 'Tensile_Strength_In_Plane_9_Units', 'Tensile_Strength_In_Plane_9_Source', 'Tensile_Strength_In_Plane_9_STP', 'Tensile_Strength_In_Plane_9_Reference', 'Tensile_Strength_In_Plane_9_Last_Modified', 'Tensile_Modulus_Thru_the_Thickness_10_Value', 'Tensile_Modulus_Thru_the_Thickness_10_Units', 'Tensile_Modulus_Thru_the_Thickness_10_Source', 'Tensile_Modulus_Thru_the_Thickness_10_STP', 'Tensile_Modulus_Thru_the_Thickness_10_Last_Modified', 'Tensile_Modulus_In_Plane_11_Value', 'Tensile_Modulus_In_Plane_11_Units', 'Tensile_Modulus_In_Plane_11_Source', 'Tensile_Modulus_In_Plane_11_STP', 'Tensile_Modulus_In_Plane_11_Last_Modified', 'Compressive_Strength_In_Plane_Value', 'Compressive_Strength_In_Plane_Units', 'Compressive_Strength_In_Plane_Source', 'Compressive_Strength_In_Plane_STP', 'Compressive_Strength_In_Plane_Reference', 'Compressive_Strength_In_Plane_Last_Modified', 'Shear_Strength_Isotropic_12_Value', 'Shear_Strength_Isotropic_12_Units', 'Shear_Strength_Isotropic_12_Source', 'Shear_Strength_Isotropic_12_STP', 'Shear_Strength_Isotropic_12_Reference', 'Shear_Strength_Isotropic_12_Last_Modified', 'Poisson_s_Ratio_Isotropic_13_Value', 'Poisson_s_Ratio_Isotropic_13_Units', 'Poisson_s_Ratio_Isotropic_13_Source', 'Poisson_s_Ratio_Isotropic_13_STP', 'Poisson_s_Ratio_Isotropic_13_Last_Modified', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Value', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Units', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Source', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_STP', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Reference', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Last_Modified', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Value', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Units', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Source', 'Coefficient_of_Thermal_Expansion_In_Plane_15_STP', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Reference', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Last_Modified', 'Emissivity1_Value', 'Emissivity1_Units', 'Emissivity1_Uncertainty', 'Emissivity1_Source', 'Emissivity1_STP', 'Emissivity1_Reference', 'Emissivity1_Last_Modified', 'Absorptivity2_Value', 'Absorptivity2_Units', 'Absorptivity2_Uncertainty', 'Absorptivity2_Source', 'Absorptivity2_STP', 'Absorptivity2_Reference', 'Absorptivity2_Last_Modified', 'Tensile_Strength_Isotropic_3_Value', 'Tensile_Strength_Isotropic_3_Units', 'Tensile_Strength_Isotropic_3_Uncertainty', 'Tensile_Strength_Isotropic_3_Source', 'Tensile_Strength_Isotropic_3_STP', 'Tensile_Strength_Isotropic_3_Reference', 'Tensile_Strength_Isotropic_3_Last_Modified', 'Tensile_Modulus_Isotropic_4_Value', 'Tensile_Modulus_Isotropic_4_Units', 'Tensile_Modulus_Isotropic_4_Uncertainty', 'Tensile_Modulus_Isotropic_4_Source', 'Tensile_Modulus_Isotropic_4_STP', 'Tensile_Modulus_Isotropic_4_Reference', 'Tensile_Modulus_Isotropic_4_Last_Modified', 'Thermal_Conductivity_Isotropic_1_Value', 'Thermal_Conductivity_Isotropic_1_Units', 'Thermal_Conductivity_Isotropic_1_Source', 'Thermal_Conductivity_Isotropic_1_STP', 'Thermal_Conductivity_Isotropic_1_Reference', 'Thermal_Conductivity_Isotropic_1_Last_Modified', 'Specific_Heat2_Value', 'Specific_Heat2_Units', 'Specific_Heat2_Source', 'Specific_Heat2_STP', 'Specific_Heat2_Reference', 'Specific_Heat2_Last_Modified', 'Thermal_Conductivity_Isotropic_Value', 'Thermal_Conductivity_Isotropic_Units', 'Thermal_Conductivity_Isotropic_Source', 'Thermal_Conductivity_Isotropic_STP', 'Thermal_Conductivity_Isotropic_Reference', 'Thermal_Conductivity_Isotropic_Last_Modified', 'Emissivity_Value', 'Emissivity_Units', 'Emissivity_Source', 'Emissivity_STP', 'Emissivity_Reference', 'Emissivity_Last_Modified', 'Single_Use_Temperature_Limit_Value', 'Single_Use_Temperature_Limit_Units', 'Single_Use_Temperature_Limit_Source', 'Single_Use_Temperature_Limit_STP', 'Single_Use_Temperature_Limit_Reference', 'Single_Use_Temperature_Limit_Last_Modified', 'Thermal_Conductivity_Isotropic_Uncertainty', 'Multiple_Use_Temperature_Limit_Value', 'Multiple_Use_Temperature_Limit_Units', 'Multiple_Use_Temperature_Limit_Source', 'Multiple_Use_Temperature_Limit_STP', 'Multiple_Use_Temperature_Limit_Last_Modified', 'Purchase_Cost_Value', 'Purchase_Cost_Units', 'Purchase_Cost_Source', 'Purchase_Cost_STP', 'Purchase_Cost_Last_Modified', 'Installation_Time_Value', 'Installation_Time_Units', 'Installation_Time_Source', 'Installation_Time_STP', 'Installation_Time_Last_Modified', 'Inspection_Repair_Time_per_Flight_Value', 'Inspection_Repair_Time_per_Flight_Units', 'Inspection_Repair_Time_per_Flight_Source', 'Inspection_Repair_Time_per_Flight_STP', 'Inspection_Repair_Time_per_Flight_Last_Modified', 'Replacement_Fraction_per_Flight_Value', 'Replacement_Fraction_per_Flight_Units', 'Replacement_Fraction_per_Flight_Source', 'Replacement_Fraction_per_Flight_STP', 'Replacement_Fraction_per_Flight_Last_Modified', 'Reuse_Flight_Limit_of_flights_Value', 'Reuse_Flight_Limit_of_flights_Units', 'Reuse_Flight_Limit_of_flights_Source', 'Reuse_Flight_Limit_of_flights_STP', 'Reuse_Flight_Limit_of_flights_Last_Modified']
Prop name candidates: ['Category', 'General_References', 'Tensile_Strength_Isotropic_1_Value', 'Tensile_Strength_Isotropic_1_Units', 'Tensile_Strength_Isotropic_1_Uncertainty', 'Tensile_Strength_Isotropic_1_Source', 'Tensile_Strength_Isotropic_1_STP', 'Tensile_Strength_Isotropic_1_Reference', 'Tensile_Strength_Isotropic_1_Last_Modified', 'Tensile_Yield_Strength_Isotropic_2_Value', 'Tensile_Yield_Strength_Isotropic_2_Units', 'Tensile_Yield_Strength_Isotropic_2_Uncertainty', 'Tensile_Yield_Strength_Isotropic_2_Source', 'Tensile_Yield_Strength_Isotropic_2_STP', 'Tensile_Yield_Strength_Isotropic_2_Reference', 'Tensile_Yield_Strength_Isotropic_2_Last_Modified', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Value', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Units', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Uncertainty', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Source', 'Coefficient_of_Thermal_Expansion_Isotropic_3_STP', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Reference', 'Coefficient_of_Thermal_Expansion_Isotropic_3_Last_Modified', 'Single_Use_Temperature_Limit5_Value', 'Single_Use_Temperature_Limit5_Units', 'Single_Use_Temperature_Limit5_Source', 'Single_Use_Temperature_Limit5_STP', 'Single_Use_Temperature_Limit5_Last_Modified', 'Tensile_Strength_Thru_the_Thickness_8_Value', 'Tensile_Strength_Thru_the_Thickness_8_Units', 'Tensile_Strength_Thru_the_Thickness_8_Source', 'Tensile_Strength_Thru_the_Thickness_8_STP', 'Tensile_Strength_Thru_the_Thickness_8_Reference', 'Tensile_Strength_Thru_the_Thickness_8_Last_Modified', 'Tensile_Strength_In_Plane_9_Value', 'Tensile_Strength_In_Plane_9_Units', 'Tensile_Strength_In_Plane_9_Source', 'Tensile_Strength_In_Plane_9_STP', 'Tensile_Strength_In_Plane_9_Reference', 'Tensile_Strength_In_Plane_9_Last_Modified', 'Compressive_Strength_In_Plane_Value', 'Compressive_Strength_In_Plane_Units', 'Compressive_Strength_In_Plane_Source', 'Compressive_Strength_In_Plane_STP', 'Compressive_Strength_In_Plane_Reference', 'Compressive_Strength_In_Plane_Last_Modified', 'Shear_Strength_Isotropic_12_Value', 'Shear_Strength_Isotropic_12_Units', 'Shear_Strength_Isotropic_12_Source', 'Shear_Strength_Isotropic_12_STP', 'Shear_Strength_Isotropic_12_Reference', 'Shear_Strength_Isotropic_12_Last_Modified', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Value', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Units', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Source', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_STP', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Reference', 'Coefficient_of_Thermal_Expansion_Thru_the_Thickness_14_Last_Modified', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Value', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Units', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Source', 'Coefficient_of_Thermal_Expansion_In_Plane_15_STP', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Reference', 'Coefficient_of_Thermal_Expansion_In_Plane_15_Last_Modified', 'Tensile_Strength_Isotropic_3_Value', 'Tensile_Strength_Isotropic_3_Units', 'Tensile_Strength_Isotropic_3_Uncertainty', 'Tensile_Strength_Isotropic_3_Source', 'Tensile_Strength_Isotropic_3_STP', 'Tensile_Strength_Isotropic_3_Reference', 'Tensile_Strength_Isotropic_3_Last_Modified', 'Single_Use_Temperature_Limit_Value', 'Single_Use_Temperature_Limit_Units', 'Single_Use_Temperature_Limit_Source', 'Single_Use_Temperature_Limit_STP', 'Single_Use_Temperature_Limit_Reference', 'Single_Use_Temperature_Limit_Last_Modified', 'Inspection_Repair_Time_per_Flight_Value', 'Inspection_Repair_Time_per_Flight_Units', 'Inspection_Repair_Time_per_Flight_Source', 'Inspection_Repair_Time_per_Flight_STP', 'Inspection_Repair_Time_per_Flight_Last_Modified', 'Replacement_Fraction_per_Flight_Value', 'Replacement_Fraction_per_Flight_Units', 'Replacement_Fraction_per_Flight_Source', 'Replacement_Fraction_per_Flight_STP', 'Replacement_Fraction_per_Flight_Last_Modified', 'Reuse_Flight_Limit_of_flights_Value', 'Reuse_Flight_Limit_of_flights_Units', 'Reuse_Flight_Limit_of_flights_Source', 'Reuse_Flight_Limit_of_flights_STP', 'Reuse_Flight_Limit_of_flights_Last_Modified']